export const SEARCH = 'OBSERVABLE/SEARCH'
export const FETCH_START = 'OBSERVABLE/FETCH_START'
export const FETCH_SUCCESS = 'OBSERVABLE/FETCH_SUCCESS'
export const FETCH_ERROR = 'OBSERVABLE/FETCH_ERROR'

export const CHANGE_PAGINATION = 'OBSERVABLE/CHANGE_PAGINATION'
export const CHANGE_SORT = 'OBSERVABLE/CHANGE_SORT'
export const CHANGE_QUERY = 'OBSERVABLE/CHANGE_QUERY'

export const LISTEN_POLLING_START = 'OBSERVABLE/LISTEN_POLLING_START'
export const POLLING_START = 'OBSERVABLE/POLLING_START'
export const POLLING_STOP = 'OBSERVABLE/POLLING_STOP'
