export const FETCH_START = 'THUNK/FETCH_START'
export const FETCH_SUCCESS = 'THUNK/FETCH_SUCCESS'
export const FETCH_ERROR = 'THUNK/FETCH_ERROR'

export const CHANGE_PAGINATION = 'THUNK/CHANGE_PAGINATION'
export const CHANGE_SORT = 'THUNK/CHANGE_SORT'
export const CHANGE_QUERY = 'THUNK/CHANGE_QUERY'

export const POLLING_START = 'THUNK/POLLING_START'
export const POLLING_STOP = 'THUNK/POLLING_STOP'
